package com.efkrdnz.magical.block.decor;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.Arrays;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import javax.imageio.ImageIO;
import net.minecraft.SharedConstants;
import net.minecraft.server.Bootstrap;
import net.minecraft.world.item.DyeColor;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.FireBlock;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

/**
 * Each decor kind is the vanilla block it stands in for, and each of its 128 blocks has every file a
 * block needs. The assets are generated by {@code scripts/decor-blocks.py} and none of the misses
 * below fails a build: a missing texture is a magenta cube, a missing loot table a block that drops
 * nothing, a missing tag a block no pickaxe will harvest - all only visible by playing.
 */
class DecorKindTest {

    @BeforeAll
    static void bootstrap() {
        SharedConstants.tryDetectVersion();
        Bootstrap.bootStrap();
    }

    /** The block each kind claims to be, for what it takes to break and what it survives. */
    private static Block analogue(DecorKind kind) {
        return switch (kind) {
            case RUNESTONE_BRICKS, RUNESTONE_TILES -> Blocks.STONE_BRICKS;
            case SIGIL_STONE -> Blocks.CHISELED_STONE_BRICKS;
            case GLIMMER_LAMP -> Blocks.GLOWSTONE;
            case CRYSTAL -> Blocks.AMETHYST_BLOCK;
            case WOVEN_CLOTH -> Blocks.WHITE_WOOL;
            case PAINTED_PLANKS -> Blocks.OAK_PLANKS;
            case ARCANE_PLATING -> Blocks.IRON_BLOCK;
        };
    }

    @Test
    void everyKindBreaksAndSurvivesLikeItsVanillaAnalogue() {
        for (DecorKind kind : DecorKind.values()) {
            Block vanilla = analogue(kind);
            assertEquals(vanilla.defaultDestroyTime(), kind.hardness(), kind + " hardness");
            assertEquals(vanilla.getExplosionResistance(), kind.resistance(), kind + " blast resistance");
            assertEquals(vanilla.defaultBlockState().requiresCorrectToolForDrops(), kind.tool().requiresTool(),
                    kind + " needs a tool to drop");
        }
    }

    @Test
    void theLampLightsLikeGlowstoneAndTheFabricsBurnLikeTheirs() {
        assertEquals(Blocks.GLOWSTONE.defaultBlockState().getLightEmission(), DecorKind.GLIMMER_LAMP.light());
        FireBlock fire = (FireBlock) Blocks.FIRE;
        assertEquals(fire.getBurnOdds(Blocks.WHITE_WOOL.defaultBlockState()), DecorKind.WOVEN_CLOTH.flammability());
        assertEquals(fire.getIgniteOdds(Blocks.WHITE_WOOL.defaultBlockState()), DecorKind.WOVEN_CLOTH.encouragement());
        assertEquals(fire.getBurnOdds(Blocks.OAK_PLANKS.defaultBlockState()), DecorKind.PAINTED_PLANKS.flammability());
        assertEquals(fire.getIgniteOdds(Blocks.OAK_PLANKS.defaultBlockState()), DecorKind.PAINTED_PLANKS.encouragement());
        for (DecorKind kind : DecorKind.values()) {
            boolean fabric = kind == DecorKind.WOVEN_CLOTH || kind == DecorKind.PAINTED_PLANKS;
            assertEquals(fabric, kind.flammable(), kind + " burns only if it is cloth or wood");
        }
    }

    @Test
    void everyBlockHasItsTextureModelsLootAndName() throws IOException {
        String lang = text("/assets/magical/lang/en_us.json");
        for (DecorKind kind : DecorKind.values()) {
            for (DyeColor colour : DecorKind.COLOURS) {
                String path = kind.path(colour);
                BufferedImage sprite = image(path);
                assertEquals(16, sprite.getWidth(), path);
                assertEquals(16, sprite.getHeight(), path);
                JsonObject model = json("/assets/magical/models/block/" + path + ".json");
                assertEquals("magical:block/decor/" + path, model.getAsJsonObject("textures").get("all").getAsString(), path);
                assertEquals(kind.translucent(), model.has("render_type"), path + " draws translucent exactly when it is crystal");
                assertEquals("magical:block/" + path, json("/assets/magical/blockstates/" + path + ".json")
                        .getAsJsonObject("variants").getAsJsonObject("").get("model").getAsString(), path);
                assertNotNull(DecorKindTest.class.getResource("/assets/magical/items/" + path + ".json"), path + " item");
                assertEquals("magical:" + path, json("/data/magical/loot_table/blocks/" + path + ".json")
                        .getAsJsonArray("pools").get(0).getAsJsonObject().getAsJsonArray("entries").get(0)
                        .getAsJsonObject().get("name").getAsString(), path + " drops itself");
                assertTrue(lang.contains("\"block.magical." + path + "\""), path + " has a name");
            }
        }
        assertTrue(lang.contains("\"itemGroup.magical.decor\""), "the tab has a name");
    }

    @Test
    void onlyTheCrystalIsSeeThrough() throws IOException {
        for (DecorKind kind : DecorKind.values()) {
            for (DyeColor colour : DecorKind.COLOURS) {
                BufferedImage sprite = image(kind.path(colour));
                boolean clear = false;
                for (int y = 0; y < 16; y++) {
                    for (int x = 0; x < 16; x++) {
                        clear |= (sprite.getRGB(x, y) >>> 24) < 255;
                    }
                }
                assertEquals(kind.translucent(), clear, kind.path(colour));
            }
        }
    }

    @Test
    void noTwoSpritesAreTheSame() throws IOException {
        Map<Integer, String> seen = new HashMap<>();
        for (DecorKind kind : DecorKind.values()) {
            for (DyeColor colour : DecorKind.COLOURS) {
                BufferedImage sprite = image(kind.path(colour));
                int hash = Arrays.hashCode(sprite.getRGB(0, 0, 16, 16, null, 0, 16));
                String before = seen.put(hash, kind.path(colour));
                assertEquals(null, before, kind.path(colour) + " is drawn the same as " + before);
            }
        }
    }

    @Test
    void theToolTagsMatchTheKinds() throws IOException {
        Set<String> pickaxe = tag("mineable/pickaxe");
        Set<String> axe = tag("mineable/axe");
        Set<String> stone = tag("needs_stone_tool");
        Set<String> wool = tag("wool");
        for (DecorKind kind : DecorKind.values()) {
            for (DyeColor colour : DecorKind.COLOURS) {
                String id = "magical:" + kind.path(colour);
                DecorKind.Tool tool = kind.tool();
                assertEquals(tool == DecorKind.Tool.PICKAXE || tool == DecorKind.Tool.STONE_PICKAXE, pickaxe.contains(id), id + " pickaxe");
                assertEquals(tool == DecorKind.Tool.AXE, axe.contains(id), id + " axe");
                assertEquals(tool == DecorKind.Tool.STONE_PICKAXE, stone.contains(id), id + " stone tool");
                assertEquals(kind == DecorKind.WOVEN_CLOTH, wool.contains(id), id + " shears");
            }
        }
    }

    private static Set<String> tag(String name) throws IOException {
        JsonArray values = json("/data/minecraft/tags/block/" + name + ".json").getAsJsonArray("values");
        Set<String> out = new HashSet<>();
        values.forEach(value -> out.add(value.getAsString()));
        return out;
    }

    private static BufferedImage image(String path) throws IOException {
        try (InputStream in = DecorKindTest.class.getResourceAsStream("/assets/magical/textures/block/decor/" + path + ".png")) {
            assertNotNull(in, path + " has no texture");
            return ImageIO.read(in);
        }
    }

    private static JsonObject json(String resource) throws IOException {
        try (InputStream in = DecorKindTest.class.getResourceAsStream(resource)) {
            assertNotNull(in, resource + " is missing");
            return JsonParser.parseReader(new InputStreamReader(in, StandardCharsets.UTF_8)).getAsJsonObject();
        }
    }

    private static String text(String resource) throws IOException {
        try (InputStream in = DecorKindTest.class.getResourceAsStream(resource)) {
            assertNotNull(in, resource + " is missing");
            return new String(in.readAllBytes(), StandardCharsets.UTF_8);
        }
    }
}
